name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: Amitabh-DevOps/Project-03-Jenkins-CI-CD-Project-Todo-node-app # Replace with the actual repository
        ref: master  # Replace with the desired branch or commit
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci

    - name: Install ESLint dependencies
      run: npm install --save-dev eslint @eslint/js globals
      
    - name: Run linting with auto-fix
      run: npm run lint:fix || true
      
  test:
    name: Test (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    needs: lint
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: Amitabh-DevOps/Project-03-Jenkins-CI-CD-Project-Todo-node-app # Replace with the actual repository
        ref: master  # Replace with the desired branch or commit
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Amitabh-DevOps/Project-03-Jenkins-CI-CD-Project-Todo-node-app
          ref: master
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
  
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-node-app-ci:latest .
  
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/todo-node-app-ci:latest
  
  deploy:
    name: Deploy Application (Docker Run)
    runs-on: ubuntu-latest
    needs: build
  
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-node-app-ci:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: Amitabh-DevOps/Project-03-Jenkins-CI-CD-Project-Todo-node-app
          ref: master
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .
  
      - name: Run container
        run: |
          docker run -d --name todo-app -p 8000:8000 $IMAGE_NAME
          echo "Container started on port 8000"
  
      - name: Test container health
        run: |
          for i in {1..10}; do
            if curl -fsS http://localhost:8000; then
              echo "App is up!"
              exit 0
            fi
            echo "Waiting for container..."
            sleep 3
          done
          echo "App failed to start!"
          docker logs todo-app
          exit 1
  
      - name: Show container logs (always)
        if: always()
        run: docker logs todo-app
  
      - name: Stop container (always)
        if: always()
        run: docker rm -f todo-app


  
